language: php

cache:
  directories:
    - node_modules

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

sudo: false

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
    - php: nightly

install:
  - composer install --no-interaction
  - gem install sass
  - npm i -g npm
  - npm i -g grunt-cli
  - npm i

script:
  - grunt ci

notifications:
  email: false
  slack:
    rooms: inpsyde:Qr1HAtG5koIbTu0nnwWYofSj
    on_start: never
    on_failure: always
    on_success: change
