language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

sudo: false

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
    - php: nightly

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer dump-autoload --no-dev
  - npm install -g jscs
  - npm install -g jshint
  - npm install -g jsonlint
  - npm install -g jsvalidate
  - npm install -g sass

before_script:
  - if [[ $TRAVIS_PHP_VERSION != 'hhvm' ]]; then phpenv config-rm xdebug.ini; fi

script:
  - find . \( -name '.*rc' \) -maxdepth 1 -exec jsonlint {} \;
  - jscs Gruntfile.js
  - jshint Gruntfile.js
  - jsvalidate Gruntfile.js
  - find . \( -name '*.json' \) -maxdepth 1 -exec jsonlint {} \;
  - find src \( -name '*.php' \) -exec php -l {} \;
  - phpunit
  - find resources/scss \( -name '*.scss' \) -maxdepth 1 -exec sass --check {} \;
  - jsvalidate resources/js
  - jshint resources/js
  - jscs resources/js
  - jsvalidate src/js

notifications:
  slack:
    rooms: inpsyde:Qr1HAtG5koIbTu0nnwWYofSj
    on_start: never
    on_failure: always
    on_success: change
