language: php

sudo: false

cache:
  apt: true
  yarn: true
  directories:
    - $HOME/.composer/cache/files
    - $HOME/.npm

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

env:
  - TRAVIS_NODE_VERSION=5

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

before_install:
  - phpenv config-rm xdebug.ini || true

install:
  - composer install --no-interaction
  - nvm install $TRAVIS_NODE_VERSION
  - yarn

script:
  - yarn test

notifications:
  email: false
  slack:
    rooms: inpsyde:Qr1HAtG5koIbTu0nnwWYofSj
    on_start: never
    on_failure: always
    on_success: change
