language: php

cache:
  directories:
    - node_modules

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

sudo: false

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
    - php: nightly

before_install:
  - if [[ $TRAVIS_PHP_VERSION != 'hhvm' ]]; then phpenv config-rm xdebug.ini; fi
  - travis_retry composer self-update
  - travis_retry composer dump-autoload --no-dev

install:
  - gem install sass
  - npm install -g npm
  - npm install -g babel-cli
  - npm install -g grunt-cli
  - npm install

script:
  - grunt ci
  - babel-node tests/js/**/*.js

notifications:
  slack:
    rooms: inpsyde:Qr1HAtG5koIbTu0nnwWYofSj
    on_start: never
    on_failure: always
    on_success: change
